/* automatically generated build number */
/*                                      */
/*    DO NOT EDIT THIS FILE MANUALLY    */
/*                                      */
/* incbuild reads this file to increase */
/* the build number automatically.      */

#ifndef __build_h__
#define __build_h__

#define BUILDNUM 10

#endif

